/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_disslove_GLToolsRenderer */

#ifndef _Included_com_example_disslove_GLToolsRenderer
#define _Included_com_example_disslove_GLToolsRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_disslove_GLToolsRenderer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_disslove_GLToolsRenderer_init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_disslove_GLToolsRenderer
 * Method:    reshape
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_disslove_GLToolsRenderer_reshape
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_disslove_GLToolsRenderer
 * Method:    display
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_example_disslove_GLToolsRenderer_display
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
